# Generated by Django 3.2.2 on 2021-05-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_advertising'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertising',
            old_name='icon',
            new_name='image',
        ),
    ]
