# Generated by Django 3.2.2 on 2021-06-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210615_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertising',
            old_name='comment',
            new_name='comment_en',
        ),
        migrations.RenameField(
            model_name='advertising',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='comment',
            new_name='comment_en',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='full_name',
            new_name='full_name_en',
        ),
        migrations.AddField(
            model_name='advertising',
            name='comment_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertising',
            name='comment_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertising',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='advertising',
            name='title_uz',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='follower',
            name='comment_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='follower',
            name='comment_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='follower',
            name='full_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='follower',
            name='full_name_uz',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
